name: build-scan-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}                 # e.g. europe-west1
  AR_HOST: ${{ vars.AR_HOST }}               # e.g. europe-west1-docker.pkg.dev
  REPO: ${{ vars.REPO }}                     # e.g. services
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}     # e.g. devsecops-demo
  RUNTIME_SA: ${{ vars.RUNTIME_SA }}         # runtime-sa@<project>.iam.gserviceaccount.com

  IMAGE_SHA: ${{ vars.SERVICE_NAME }}:${{ github.sha }}
  IMAGE_LATEST: ${{ vars.SERVICE_NAME }}:latest
  AR_IMAGE_SHA: ${{ vars.AR_HOST }}/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}
  AR_IMAGE_LATEST: ${{ vars.AR_HOST }}/${{ vars.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.SERVICE_NAME }}:latest

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOY_SA }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "$AR_HOST" --quiet

      # Dockerfile в корне репозитория
      - name: Build image
        run: docker build -t "$IMAGE_SHA" -f Dockerfile .

      # Локальная проверка образа на раннере — ловит ошибки ещё до деплоя
      - name: Local smoke (container listens & endpoints)
        run: |
          set -euo pipefail
          docker run -d --name app -p 8080:8080 "$IMAGE_SHA"
          # ждём порт
          for i in {1..20}; do
            if curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then break; fi
            sleep 1
          done
          curl -fsS http://127.0.0.1:8080/ | grep -q '^ok$'
          curl -fsS http://127.0.0.1:8080/healthz | grep -q '^ok$'
          curl -fsS http://127.0.0.1:8080/info | grep -q 'APP_TOKEN=' || true  # локально секрета нет — не блокируем
          docker rm -f app

      # Без фейла пайплайна — только отчёт
      - name: Trivy scan (report only)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_SHA }}
          format: table
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      - name: SBOM (CycloneDX)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_SHA }}
          format: cyclonedx
          output: sbom.cdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json

      - name: Tag & push to Artifact Registry
        run: |
          docker tag "$IMAGE_SHA" "$AR_IMAGE_SHA"
          docker tag "$IMAGE_SHA" "$AR_IMAGE_LATEST"
          docker push "$AR_IMAGE_SHA"
          docker push "$AR_IMAGE_LATEST"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$AR_IMAGE_SHA" \
            --region "$REGION" \
            --service-account "$RUNTIME_SA" \
            --allow-unauthenticated \
            --platform managed \
            --port 8080 \
            --max-instances 3 \
            --timeout 300

      - name: Show Cloud Run URL
        run: gcloud run services describe "$SERVICE_NAME" --region "$REGION" --format='value(status.url)'

      - name: Smoke check (Cloud Run, robust)
        run: |
          set -euo pipefail
          svc_url="$(gcloud run services describe "$SERVICE_NAME" --region "$REGION" --format='value(status.url)')"
          echo "Testing URL: $svc_url"

          # ждём Ready до 6 минут (72 * 5 сек)
          attempts=0
          until gcloud run services describe "$SERVICE_NAME" --region "$REGION" \
                 --format='get(status.conditions[?type="Ready"].status)' | grep -q '^True$'; do
            attempts=$((attempts+1))
            if [ "$attempts" -gt 72 ]; then
              echo "Service did not become Ready in time" >&2
              exit 1
            fi
            echo "Waiting for Ready... ($attempts/72)"
            sleep 5
          done

          check() {
            local path="$1" expect="$2"
            local max=12
            for i in $(seq 1 $max); do
              resp="$(curl -fsS -L "$svc_url$path" -w '\n%{http_code}' --connect-timeout 5 --max-time 10 || true)"
              code="$(printf '%s\n' "$resp" | tail -n1)"
              body="$(printf '%s\n' "$resp" | sed '$d')"
              echo "[$path] http=$code payload=$(echo "$body" | head -c 120 | tr '\n' ' ')"
              if [ "$code" = "200" ]; then
                case "$expect" in
                  ok)        printf '%s' "$body" | tr -d '\r' | grep -q '^ok$' && return 0 ;;
                  has_token) printf '%s' "$body" | grep -q 'APP_TOKEN=' && return 0 ;;
                esac
              fi
              sleep $(( i < 6 ? 3 : 6 ))
            done
            echo "Check $path failed after $max attempts" >&2
            echo "Last body:"; echo "$body"
            return 1
          }

          check "/"        ok
          check "/healthz" ok
          check "/info"    has_token

          echo "Cloud Run smoke passed ✅"

      # Автосбор диагностики, если что-то упало
      - name: Debug — service/revision conditions & logs
        if: failure()
        run: |
          set -x
          gcloud run services describe "$SERVICE_NAME" --region "$REGION" \
            --format='yaml(spec.template.spec.containers[0].image,status.conditions,status.traffic)'
          rev="$(gcloud run revisions list --service "$SERVICE_NAME" --region "$REGION" --format='value(name)' --limit=1)"
          echo "Latest revision: $rev"
          gcloud run revisions describe "$rev" --region "$REGION" --format='yaml(status.conditions)'
          gcloud logging read \
            'resource.type="cloud_run_revision" AND resource.labels.service_name="${{ env.SERVICE_NAME }}"' \
            --project "$PROJECT_ID" --limit 50 --format='value(timestamp, textPayload)'
