name: oidc-check
on: [workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOY_SA }}
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Who am I
        run: gcloud auth list --filter=status:ACTIVE --format='value(account)'
